### ISSUE TITLE
Working example of 'workflow' tests

### ISSUE THREAD

**Issue by LukeGoodsell** [askimed/nf-test#10]
Posting the issue discussed [here](https://twitter.com/luke_goodsell/status/1562202613298462720):

Please can you share a working example of a test case for `workflow` objects? No matter how we try following the [documentation](https://code.askimed.com/nf-test/testcases/nextflow_workflow/), we get a `groovy.lang.MissingMethodException`:

**trial.nf**:
```nextflow
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

process sayHello {
    input:
        val cheers

    output:
        stdout emit: verbiage

    script:
    """
    echo -n $cheers
    """
}

workflow trial {
    take: things
    main:
        sayHello(things)
        sayHello.out.verbiage.view()
}

workflow {
    Channel.from(['a']) | trial
}
```

**trial.nf.test**:
```nextflow
nextflow_workflow {

    name "Test workflow"
    script "trial.nf"
    workflow "trial"

    test("Should run without failures") {
        when {
            params {
                outdir = "tests/results"
            }
            workflow {
                """
                input[0] = ["a"]
                """
            }
        }

        then {
            //check if test case succeeded
            assert workflow.success
        }
    }
}
```

**Output**:
```
$ ./nf-test test trial.nf.test

🚀 nf-test 0.5.1
https://code.askimed.com/nf-test
(c) 2021 - 2022 Lukas Forer and Sebastian Schoenherr


Test workflow

  Test [57acc7c1] 'Should run without failures' FAILED (0.01s)

  groovy.lang.MissingMethodException: No signature of method: trial_nf$_run_closure1$_closure2.workflow() is applicable for argument types: (trial_nf$_run_closure1$_closure2$_closure3$_closure6) values: [trial_nf$_run_closure1$_closure2$_closure3$_closure6@4721d212]



FAILURE: Executed 1 tests in 0.018s (1 failed)
```

**Comment by lukfor** [comment]
Thanks, workflow tests are fixed in the latest version 0.6.0.

We added your example also to the documentation: https://code.askimed.com/nf-test/testcases/nextflow_workflow/

Let us know if it now works for you.

**Comment by LukeGoodsell** [comment]
Works just right, thanks @lukfor! The docs were still showing a process test, though, so I raised [this PR](https://github.com/askimed/nf-test/pull/13) to update them.
